name: Build and Generate Checksum

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  checksum:
    name: Generate checksum
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: build/bin/
          merge-multiple: true

      - name: Generate checksum
        run: make checksum

      - uses: actions/upload-artifact@v4
        with:
          name: checksum
          path: build/checksum/SHA256SUM
          if-no-files-found: error
