name: Build and Package

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package-linux:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "linux" ]
        arch: [ "arm", "arm64", "386", "amd64", "ppc64le"]
        format: ["zip", "tgz" ]
      fail-fast: true

    name: "Package ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.format }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: build/bin/

      - name: Package
        run: OS=${{ matrix.os }} ARCH=${{ matrix.arch }} VERSION=${{ needs.build.outputs.app-version }} PACKAGE_FORMAT=${{ matrix.format }} make package

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: build/package/**
          if-no-files-found: error

  package-darwin:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "darwin" ]
        arch: [ "amd64", "arm64" ]
        format: ["zip", "tgz" ]
      fail-fast: true
    
    name: "Package ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.format }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: build/bin/

      - name: Package
        run: OS=${{ matrix.os }} ARCH=${{ matrix.arch }} VERSION=${{ needs.build.outputs.app-version }} PACKAGE_FORMAT=${{ matrix.format }} make package

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: build/package/**
          if-no-files-found: error

  checksum:
    name: Generate checksum
    needs:
      - package-linux
      - package-darwin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: package
          path: build/package/

      - name: Generate checksum
        run: make checksum

      - uses: actions/upload-artifact@v3
        with:
          name: checksum
          path: build/checksum/**
          if-no-files-found: error
