name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yml
  package-artifacts:
    uses: ./.github/workflows/package.yml
  github-release:
    name: Github Release
    needs: package-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          path: build/

      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: build/archive/*
          token: ${{ secrets.GITHUB_TOKEN }}
