name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-package:
    name: Build and Package
    uses: ./.github/workflows/package.yml

  github-release:
    name: Github Release
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4.1.7
        with:
          name: package
          path: build/package/

      - uses: actions/download-artifact@v4.1.7
        with:
          name: checksum
          path: build/checksum/

      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: "build/package/*,build/checksum/*"
          token: ${{ secrets.GITHUB_TOKEN }}
