name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  checksum:
    name: Build and Release
    uses: ./.github/workflows/checksum.yml

  github-release:
    name: Github Release
    permissions:
      packages: write
      contents: write
    needs: checksum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: release_files/
          merge-multiple: true

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: Release ${{ github.ref_name }}
          prerelease: false
          files: |
            release_files/*
