name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
  
      - name: Build project
        run: |
          make build
          make archive
          cd archive && sha256sum * > SHA256SUM

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            archive/consul-snapshotter_linux_amd64.zip
            archive/consul-snapshotter_darwin_amd64.zip
            archive/consul-snapshotter_linux_amd64.tar.gz
            archive/consul-snapshotter_darwin_amd64.tar.gz
            archive/SHA256SUM
